version: '3.8'

services:
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9112:9112"
    volumes:
      - ./web:/app/web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9112/metrics"]
      interval: 30s
      timeout: 3s
      retries: 3