{
 "title": "Service Status Exporter Dashboard",
 "description": "一个轻量级的服务状态监控工具，专为微服务架构设计。通过HTTP请求监控关键业务服务的可用性和响应性能，暴露Prometheus兼容的指标，可与Grafana等可视化工具无缝集成。",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "监控服务状态",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "services_status_exporter_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "当前监控站点数量",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(site_up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "连通性占比",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "(\r\n  count by (status) (\r\n    label_replace(site_up, \"status\", \"up\", \"\", \"\") == 1\r\n    or\r\n    label_replace(site_up, \"status\", \"down\", \"\", \"\") == 0\r\n  )\r\n  / \r\n  scalar(count(site_up))\r\n) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "请求方法占比",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count by (method) (site_up) / scalar(count(site_up)) * 100"
    }
   ]
  },
  {
   "title": "状态列表",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "site_up - 0" },
    {
     "expr": "site_request_duration_seconds - 0"
    },
    {
     "expr": "sum_over_time(site_up[1h])/count_over_time(site_up[1h])"
    }
   ]
  },
  {
   "title": "最近24小时的响应时间(s)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "avg_over_time(site_request_duration_seconds[5m]) * 1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "最近24小时可用性",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum_over_time(site_up[24h])/count_over_time(site_up[24h]) * 100",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}